# Generated by Django 3.0.4 on 2020-03-05 05:05

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=1000000, verbose_name='Tittle')),
                ('description', models.TextField(max_length=1000000000, verbose_name='Description')),
                ('published_date', models.DateTimeField(auto_now_add=True, verbose_name='Published Time')),
                ('image', models.ImageField(upload_to=api.models.image_handler, verbose_name='Image')),
                ('category', models.CharField(max_length=100000, verbose_name='Category')),
                ('tag', models.CharField(max_length=10000, verbose_name='Tag')),
            ],
        ),
        migrations.CreateModel(
            name='CommentsViews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.IntegerField(blank=True, default=0, verbose_name='Views')),
                ('Comments', models.CharField(max_length=100000, verbose_name='Comments')),
                ('name', models.CharField(max_length=1000, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('like', models.IntegerField(blank=True, default='0', verbose_name='Title')),
                ('FoodItem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.FoodItem')),
            ],
        ),
    ]
