# Generated by Django 3.0.4 on 2020-03-05 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentsviews',
            name='approved_comment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commentsviews',
            name='parent',
            field=models.IntegerField(default=0),
        ),
    ]
