# Generated by Django 3.0.4 on 2020-03-05 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200305_0521'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='author',
            field=models.CharField(default='Anjali', max_length=10000, verbose_name='Author'),
            preserve_default=False,
        ),
    ]
