# Generated by Django 3.0.4 on 2020-03-05 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_fooditem_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='category',
            field=models.CharField(choices=[('Non-veg', 'Non-veg'), ('Veg', 'Veg'), ('BreakFast', 'BreakFast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner')], max_length=100000, verbose_name='Category'),
        ),
    ]
