# Generated by Django 3.0.4 on 2020-03-05 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200305_0738'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=10000, verbose_name='Category')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
            ],
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='category',
            field=models.CharField(choices=[('Non-veg', 'Non-veg'), ('Veg', 'Veg'), ('BreakFast', 'BreakFast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Salad', 'Salad'), ('Sweet', 'Sweet'), ('Pudding', 'Pudding'), ('Soup', 'Soup'), ('Snacks', 'Snacks')], max_length=100000, verbose_name='Category'),
        ),
    ]
